FROM puppet/pdk:3.0.1.3

LABEL maintainer "Raphael Lekies <raphael.lekies@it4smart.eu> (IT4smart GmbH)"

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>


COPY post-start.sh /root/post-start.sh